spring.data.mongodb.port: 0

de.flapdoodle.mongodb.embedded.version: 7.0.8
grpc:
  client:
    crypto-service-grpc:
      address: 'static://localhost:9092'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
