spring.application.name: crypto-exchange-grpc

spring.data.mongodb:
  host: localhost
  port: 27017
  database: crypto-currencies

crypto-api:
  url: https://api.minerstat.com/v2
  scheduler:
    delay-minutes: 60
    init-delay-minutes: 1